# --- Stop Words ---
greek_stopwords = {
    "καί",
    "δέ",
    "γάρ",
    "μέν",
    "οὐ",
    "εἰ",
    "ὡς",
    "ἵνα",
    "ἐν",
    "τοῦ",
    "τὸν",
    "τῆς",
    "τῇ",
    "ὁ",
    "ἡ",
    "τὸ",
    "οἱ",
    "αὐτός",
    "τις",
    "τι",
    "εἰμί",
    "ἐκ",
    "πρός",
    "διά",
    "ἀλλά",
    "οὐδείς",
    "μή",
    "ἄν",
    "ἐπί",
    "τε",
    "οὕτως",
    "εἶναι",
    "σὺν",
    "ὅς",
    "ἐντός",
}

# --- Glossary ---
lemma_glosses = {
    "θεός": "God",
    "ἐγώ": "I",
    "σύ": "you (sg)",
    "εἰς": "into/to",
    "νόμος": "law",
    "πᾶς": "all/every",
    "Χριστός": "Christ",
    "ὅτι": "that/because",
    "οὗτος": "this",
    "ἁμαρτία": "sin",
    "λέγω": "I say",
    "οὖν": "therefore",
    "κατά": "according to",
    "κύριος": "Lord",
    "τίς": "who/what",
    "πίστις": "faith",
    "γίνομαι": "to become",
    "Ἰησοῦς": "Jesus",
    "πνεῦμα": "spirit",
    "δικαιοσύνη": "righteousness",
}

# --- POS Label Map ---
MAPS = {
    "Part_Of_Speech": {
        "A-": "Adjective",
        "C-": "Conjunction",
        "D-": "Adverb",
        "I-": "Interjection",
        "N-": "Noun",
        "P-": "Preposition",
        "RA": "Definite Article",
        "RD": "Demonstrative Pronoun",
        "RI": "Interrog./Indef. Pronoun",
        "RP": "Personal Pronoun",
        "RR": "Relative Pronoun",
        "V-": "Verb",
        "X-": "Particle",
    },
    "Person": {"1": "First", "2": "Second", "3": "Third", "-": "Unspecified"},
    "Tense": {
        "P": "Present",
        "I": "Imperfect",
        "F": "Future",
        "A": "Aorist",
        "X": "Perfect",
        "Y": "Pluperfect",
        "-": "Unspecified",
    },
    "Voice": {"A": "Active", "M": "Middle", "P": "Passive", "-": "Unspecified"},
    "Mood": {
        "I": "Indicative",
        "D": "Imperative",
        "S": "Subjunctive",
        "O": "Optative",
        "N": "Infinitive",
        "P": "Participle",
        "-": "Unspecified",
    },
    "Case": {
        "N": "Nominative",
        "G": "Genitive",
        "D": "Dative",
        "A": "Accusative",
        "-": "Unspecified",
    },
    "Number": {"S": "Singular", "P": "Plural", "-": "Unspecified"},
    "Gender": {"M": "Masculine", "F": "Feminine", "N": "Neuter", "-": "Unspecified"},
    "Degree": {"C": "Comparative", "S": "Superlative", "-": "Unspecified"},
}
